name: Azure Web App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Docker Login to ACR
      run: |
        echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login group15registry.azurecr.io -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t group15registry.azurecr.io/azureweb:latest .

    - name: Push Docker Image
      run: docker push group15registry.azurecr.io/azureweb:latest

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'helloApp-CB'
        images: 'group15registry.azurecr.io/azureweb:latest'
